config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :users
  root to: "books#index"
  get '/' => 'books#index'
  get '/login' => 'users#login'
  post '/login' => 'users#login'
  get '/logout' => 'users#logout'
  get '/library' => 'books#library'
  get '/lent/:id' => 'books#lent' ,as: :book_lent
  get '/return/:id' => 'books#return' ,as: :book_return
  get '/mybooks' => 'books#mybooks'
  get '/contact' => 'users#contact'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :user_books, :foreign_key => :book_id
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username
  has_many :user_books
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_filter :authorize

  def authorize
      username = cookies[:username]
      is_admin = cookies[:is_admin]
      if !username.present? || !is_admin.present?
        redirect_to "/login" and return if params["action"] != "login"
      elsif params["action"] == "login"
        page = is_admin ? "/" : "/library"
          redirect_to page and return
      end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :user, except: [:login, :logout]

  def library
    @books = Book.all
  end

  def lent
    book_id = params[:id]
    u = UserBook.find_or_initialize_by({:book_id => book_id, :user_id => @user.id})
    u.save!
    @lent = true
    redirect_to "/library"
  end

  def return
    book_id = params[:id]
    u = UserBook.find_by({:book_id => book_id, :user_id => @user.id})
    u.delete if u.present?
    @return = true
    redirect_to "/mybooks"
  end

  def mybooks
    #@books =Book.joins(:user_books).where("user_books.user_id = ? ",@user.id)
    render :layout =>  false
  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :status)
    end
    def user
      @user = User.find_by(username: cookies["username"])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :user, except: [:login, :logout]

  def home
  end

  def contact
    render layout: false
  end

  def login
    if params["username"].present? and params["password"].present?
      is_admin = params["is_admin"] == "admin" 
      user = User.find_by(username: params["username"], password: params["password"],is_admin: is_admin)
      if user.present?
        cookies["username"] = user.username
        cookies["is_admin"] = user.is_admin
        page = is_admin ? "/" : "/library"
        redirect_to page and return
      end
      @invalid = true
    end
    render layout: "login"
  end

  def logout
    cookies.delete(:username)
    cookies.delete(:is_admin)
    redirect_to "/" and return
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :is_admin)
    end

    def user
      @user = User.find_by(username: cookies["username"])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => "form-horizontal book" } do |f| %>

  <% if @book.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :available, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :status, :class => '' %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:Availability) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.id, book_path(book) %></td>
        <td><%= book.name %></td>
        <td><%= book.status %></td>
        <td><%=l book.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      book_path(book), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_book_path(book), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      book_path(book),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_book_path,
            :class => 'btn btn-primary' %>

app/views/books/library.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1>Library</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:book_name) %></th>
      <th><%= model_class.human_attribute_name(:action) %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <% disabled = book.user_books.where(:user_id=>@user.id).first.present? %>
    <% lent = disabled ? "lented" : "lent" %>
      <tr>
        <td><%= link_to book.id, book_path(book) %></td>
        <td><%= book.name %></td>
        <td>
        <% if book.status %>
          <%= link_to t('.lent', :default => lent),
                      book_lent_path(book), :class => 'btn btn-default btn-xs', :disabled => disabled %>
        <% else %>
        Not Available
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <% if @lent %>

<script type="text/javascript">
alert("book lented")
</script>

  <% end %>

app/views/books/mybooks.erb
<%= 
(`php lib/mybooks.php #{@user.id}`).html_safe %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @book.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @book.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Book Portal</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
      <% if @user.is_admin %>
        <li class="<%= controller.class == UsersController ? 'active' : '' %>"><a href="/users">USERS</a></li>
        <li class="<%= controller.class == BooksController ? 'active' : '' %>"><a href="/books">BOOKS</a></li>
      <% else %>
        <li class="<%= controller.class == BooksController and controller.action_name == 'library' ? 'active' : '' %>"><a href="/library">LIBRARY</a></li>
        <li class="<%= controller.class == BooksController and controller.action_name == 'mybooks' ? 'active' : '' %>"><a href="/mybooks">MY BOOKS</a></li>
        <li><a href="/contact">CONTACT US</a></li>
      <% end %>
        <li><a href="/logout">LOGOUT</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<%= yield %>
  
</div>
</div>
</div>

</body>
</html>

app/views/layouts/login.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :username, :class => 'form-control' %>
    </div>
    <%=f.error_span(:username) %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.hidden_field :is_admin, :class => 'form-control', :value=> false %>
    </div>
    <%=f.error_span(:is_admin) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/contact.erb
<%= 
(`python lib/contact.py`).html_safe %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/home.erb
test

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:is_admin) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.is_admin %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/login.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
   

    </div>
  </div>
</nav>
<div class="container">

        <p><br/></p>
        <div class="row">
    
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                            <div class="page-header text-center">
                            <h3>Login</h3>
                        </div>
                        <div class="alert alert-danger alert-dismissible fade in notice-alert" style="<%= 'display:none' unless @invalid.present? %>"role="alert"> Invalid Username/password<button type="button" class="close" onclick="$(this).closest('.alert').hide()"><span aria-hidden="true">×</span></button> 
                          <span id="alert-message">
                            <%= @notice %>
                          </span>
                        </div>
                        <form role="form" action="./login" method="post">
                            <div class="form-group">
                                    <label for="exampleInputEmail1">USERNAME</label>
                                    <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                    <input type="text" class="form-control LoNotSensitive" name="username" required placeholder="Enter email">
                                </div>
                            </div>
                            <input type="hidden" name="redirect_to" value="<%= @redirect_to %>"></input>
                            <div class="form-group">
                                    <label for="exampleInputPassword1">PASSWORD</label>
                                    <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-star"></span></span>
                                    <input type="password" class="form-control" name="password" required placeholder="Password">
                                </div>
                            </div>
                            <label class="radio-inline"><input type="radio" name="is_admin" value="admin" checked>Admin</label>
                            <label class="radio-inline"><input type="radio" name="is_admin" value="user">User</label>
                            
                            <hr/>
                            <button id="loginButton" type="submit" class="btn btn-primary "><span class="glyphicon glyphicon-lock"></span> Login</button>
                            <p><br/></p>
                        </form>
                        <div class="modal fade bs-example-modal-sm" id="myPleaseWait" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">
                                            <span class="glyphicon glyphicon-time">
                                            </span>Please Wait
                                        </h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-info
                                            progress-bar-striped active" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_admin) %>:</strong></dt>
  <dd><%= @user.is_admin %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>